### ISSUE TITLE
Please use a freely licensed logo instead of the clojure one in tests

### ISSUE THREAD

**Issue by baldurmen** [tebeka/clj-digest#11]
Hi!

It seems you are using the clojure logo in your tests. Sadly, said logo cannot be redistributed freely :(

https://grokbase.com/t/gg/clojure/153kzdtgk1/logo-licensing
https://groups.google.com/forum/#!topic/clojure/_o-sHr_YIwo

This mean that when I package this library in Debian, I need to repack your source code to remove it, and then replace the logo with something else.

I propose you use the Debian logo instead! It's under the GPLv3 and can be freely redistribued :)  https://www.debian.org/logos/

If that works for you, I'd be happy to send a patch your way.

Cheers, and thanks for maintaining this library!

**Comment by baldurmen** [comment]
Well, now that I think of it, using the Debian logo would make the licence on this library much more complex :)

I'd be happy to make a PR to replace it by a file I'll license under the EPL then.

**Comment by tebeka** [comment]
Thanks for bringing it to my attention!

I think I'll get one of my own pictures - this way no license issue at all. Give me a couple of days or submit a patch with a CC0 or public domain image.

**Comment by tebeka** [comment]
Fixed in 8e8f03e0d7d4e49711238443e99116bc9da091bf
